Build malloc from libcmt for goldp ourselves (#358)
* ci: generate message in pull requests (#497)

* ci: remove --nolib from reccmp-reccmp

* Remove ansi color codes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -43,23 +43,26 @@ jobs:
     runs-on: windows-latest
 
     steps:
-    - uses: actions/checkout@v6
+    - name: 'Checkout racers sources'
+      uses: actions/checkout@v6
 
-    - uses: actions/checkout@v6
+    - name: 'Checkout MSVC6 RTM toolchain'
+      uses: actions/checkout@v6
       with:
         repository: isledecomp/MSVC600-8168
         path: msvc600
 
-    - name: Setup cmake
-      uses: jwlawson/actions-setup-cmake@v2
+    - name: 'Checkout MSVC6 SP3 toolchain'
+      uses: actions/checkout@v6
       with:
-        cmake-version: '3.25.x'
+        repository: isledecomp/MSVC600-8447
+        path: msvc600sp3
 
     - name: Build
       shell: cmd
       run: |
         call .\msvc600\VC98\Bin\VCVARS32.BAT x86
-        cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -G "NMake Makefiles"
+        cmake -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo "-DMSVC_CRT_SRC_PATH=${{ github.workspace }}/msvc600sp3/VC98/crt/src" -G "NMake Makefiles"
         cmake --build build
 
     - name: Upload Artifact
@@ -114,8 +117,8 @@ jobs:
     - name: Summarize Accuracy
       shell: bash
       run: |
-        reccmp-reccmp -S LEGORACERSPROGRESS.SVG --svg-icon assets/legoracers.png --target LEGORACERS --total 3986 --nolib --json LEGORACERSPROGRESS.json --html LEGORACERSPROGRESS.HTML
-        reccmp-reccmp -S GOLDPPROGRESS.SVG --svg-icon assets/goldp.png --target GOLDP --total 1071 --nolib --json GOLDPPROGRESS.json --html GOLDPPROGRESS.HTML
+        reccmp-reccmp -S LEGORACERSPROGRESS.SVG --svg-icon assets/legoracers.png --target LEGORACERS --total 3986 --json LEGORACERSPROGRESS.json --html LEGORACERSPROGRESS.HTML
+        reccmp-reccmp -S GOLDPPROGRESS.SVG --svg-icon assets/goldp.png --target GOLDP --total 1071 --json GOLDPPROGRESS.json --html GOLDPPROGRESS.HTML
 
     - name: Compare Accuracy With Current Master
       shell: bash
@@ -125,8 +128,8 @@ jobs:
         curl -fLSs -o LEGORACERSPROGRESS-old.json $RELEASE_URL/LEGORACERSPROGRESS.json || echo "" >LEGORACERSPROGRESS-old.json
         curl -fLSs -o GOLDPPROGRESS-old.json $RELEASE_URL/GOLDPPROGRESS.json || echo "" >GOLDPPROGRESS-old.json
 
-        (reccmp-reccmp --target LEGORACERS --nolib --diff LEGORACERSPROGRESS-old.json || echo "Current master not found")>"LEGORACERS-diff.txt"
-        (reccmp-reccmp --target GOLDP --nolib --diff GOLDPPROGRESS-old.json || echo "Current master not found")>"GOLDP-diff.txt"
+        (reccmp-reccmp --target LEGORACERS --diff LEGORACERSPROGRESS-old.json || echo "Current master not found")>"LEGORACERS-diff.txt"
+        (reccmp-reccmp --target GOLDP --diff GOLDPPROGRESS-old.json || echo "Current master not found")>"GOLDP-diff.txt"
 
         cat LEGORACERS-diff.txt
         cat GOLDP-diff.txt
@@ -162,6 +165,7 @@ jobs:
           echo "## $1"
           echo '```'
           if [ -f "$2" ]; then
+            sed -i -E 's/\x1B\[[0-9;]*[[:alpha:]]//g' "$2"
             python -c "print(open('$2').read().strip())";
           else
             echo '(no diff available)';
